runtime: nodejs20

env_variables:
  NODE_ENV: production
  PORT: 8080

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.8

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

handlers:
  # Serve static assets from the client build directory
  - url: /assets
    static_dir: client/dist/assets
    secure: always

  # Serve the favicon
  - url: /favicon.ico
    static_files: client/dist/favicon.ico
    upload: client/dist/favicon.ico
    secure: always

  # All other requests go to the Express server
  - url: /.*
    script: auto
    secure: always

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2