steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    
  # Build the client application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    
  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

options:
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  _APP_VERSION: 'latest'

# Optional: Configure automatic triggers
# You can set this up in Google Cloud Console to trigger on git pushes

timeout: '1200s'